on: push
name: Test, Build and Release
jobs:
  build:
    name: Build Website and Mobile App
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '1.7.8+hotfix.4'
    - run: flutter channel dev
    - run: flutter upgrade
    - run: flutter config --enable-web
    - run: flutter pub get
    - run: flutter create .
    - run: flutter build web
    - run: zip -r builds.zip build/
    - name: Create a Release ZIP
      uses: ncipollo/release-action@v1
      with:
        artifacts: "builds.zip"
        token: ${{ secrets.buildtoken }}
